package ui

import (
	"crypto/subtle"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/ivantit66/onebase/internal/debugger"
	"github.com/ivantit66/onebase/internal/dsl/interpreter"
	"github.com/ivantit66/onebase/internal/dsl/lexer"
	"github.com/ivantit66/onebase/internal/dsl/parser"
)

// ── JSON helpers ─────────────────────────────────────────────────

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	respondJSONTo(w, v)
}

func readJSON(r *http.Request, v any) error {
	if r.Body == nil {
		return fmt.Errorf("empty body")
	}
	defer closeRead("тело запроса", r.Body)
	return json.NewDecoder(r.Body).Decode(v)
}

// debugTokenMiddleware gates the debug API: every request must carry the shared
// internal token in X-OneBase-Debug-Token. The token is generated by the
// launcher and passed to the spawned base process via ONEBASE_DEBUG_TOKEN; the
// configurator's debug proxy attaches it. Direct unauthenticated requests
// (curl, remote attackers) are rejected — closing the prior auth-free hole.
// The single client is the server-side launcher proxy, so no CORS is needed.
func debugTokenMiddleware(token string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			got := r.Header.Get("X-OneBase-Debug-Token")
			if token == "" || subtle.ConstantTimeCompare([]byte(got), []byte(token)) != 1 {
				writeJSON(w, http.StatusUnauthorized, map[string]string{"error": "unauthorized"})
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

// ── Global Debug Handlers ────────────────────────────────────────

// debugGlobalEnable handles POST /debug/global/enable.
// Hook не присваивается интерпретатору: каждый запуск DSL сам захватывает
// текущую сессию через interp.DebugSource (см. wiring в New) — включение
// отладки на живом сервере не гонит с конкурентными запусками (план 52).
func (s *Server) debugGlobalEnable(w http.ResponseWriter, r *http.Request) {
	sess := s.globalDebug.Enable()
	writeJSON(w, 200, map[string]any{
		"status":     "enabled",
		"session":    "global",
		"dbg_ptr":    fmt.Sprintf("%p", s.globalDebug),
		"sess_ptr":   fmt.Sprintf("%p", sess),
		"interp_ptr": fmt.Sprintf("%p", s.interp),
	})
}

// debugGlobalDisable handles POST /debug/global/disable
func (s *Server) debugGlobalDisable(w http.ResponseWriter, r *http.Request) {
	s.globalDebug.Disable()
	writeJSON(w, 200, map[string]string{"status": "disabled"})
}

// debugGlobalStatus handles GET /debug/global/status
func (s *Server) debugGlobalStatus(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Cache-Control", "no-store")
	sess := s.globalDebug.Session()
	if sess == nil {
		writeJSON(w, 200, map[string]any{"state": "disabled", "dbg_ptr": fmt.Sprintf("%p", s.globalDebug)})
		return
	}
	writeJSON(w, 200, sess.Snapshot())
}

// debugGlobalBreakpoint handles POST /debug/global/breakpoint
func (s *Server) debugGlobalBreakpoint(w http.ResponseWriter, r *http.Request) {
	var req struct {
		File      string `json:"file"`
		Line      int    `json:"line"`
		Action    string `json:"action"`    // "set", "remove", "toggle"
		Condition string `json:"condition"` // выражение DSL; пусто — точка безусловная
	}
	if err := readJSON(r, &req); err != nil {
		writeJSON(w, 400, map[string]string{"error": err.Error()})
		return
	}

	sess := s.globalDebug.Session()
	if sess == nil {
		writeJSON(w, 400, map[string]string{"error": "debug not enabled"})
		return
	}

	// Синтаксис условия проверяем здесь, а не при первом проходе строки:
	// иначе про опечатку человек узнал бы посреди отладки, из журнала точки.
	condition := strings.TrimSpace(req.Condition)
	if condition != "" {
		if err := validateBreakpointCondition(condition); err != nil {
			writeJSON(w, 400, map[string]string{"error": err.Error()})
			return
		}
	}

	respond := func(bp *debugger.Breakpoint) {
		snap := sess.Snapshot()
		writeJSON(w, 200, map[string]any{
			"id": bp.ID, "file": bp.File, "line": bp.Line, "enabled": bp.Enabled,
			"condition": bp.Condition,
			"bp_count":  snap.DiagBPCount, "bp_keys": snap.DiagBPKeys,
		})
	}

	switch req.Action {
	case "set":
		respond(sess.SetBreakpoint(req.File, req.Line, condition))
	case "remove":
		sess.RemoveBreakpoint(req.File, req.Line)
		writeJSON(w, 200, map[string]string{"status": "removed"})
	case "toggle":
		if sess.FindBreakpoint(req.File, req.Line) != nil {
			sess.RemoveBreakpoint(req.File, req.Line)
			writeJSON(w, 200, map[string]string{"status": "removed"})
			return
		}
		respond(sess.SetBreakpoint(req.File, req.Line, condition))
	default:
		writeJSON(w, 400, map[string]string{"error": "unknown action: " + req.Action})
	}
}

// validateBreakpointCondition разбирает условие точки останова как выражение DSL.
func validateBreakpointCondition(expr string) error {
	p := parser.New(lexer.New(expr, "<условие точки останова>"))
	if _, err := p.ParseExpr(); err != nil {
		return fmt.Errorf("условие точки останова: %w", err)
	}
	return nil
}

// debugGlobalContinue handles POST /debug/global/continue
func (s *Server) debugGlobalContinue(w http.ResponseWriter, r *http.Request) {
	sess := s.globalDebug.Session()
	if sess == nil {
		writeJSON(w, 400, map[string]string{"error": "debug not enabled"})
		return
	}
	sess.Continue()
	writeJSON(w, 200, map[string]string{"status": "continued"})
}

// debugGlobalStep handles POST /debug/global/step
func (s *Server) debugGlobalStep(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Mode string `json:"mode"` // "into", "over", "out"
	}
	if err := readJSON(r, &req); err != nil {
		writeJSON(w, 400, map[string]string{"error": err.Error()})
		return
	}

	sess := s.globalDebug.Session()
	if sess == nil {
		writeJSON(w, 400, map[string]string{"error": "debug not enabled"})
		return
	}

	var mode debugger.StepMode
	switch req.Mode {
	case "into":
		mode = debugger.StepInto
	case "over":
		mode = debugger.StepOver
	case "out":
		mode = debugger.StepOut
	default:
		mode = debugger.StepOver
	}

	sess.Step(mode)
	writeJSON(w, 200, map[string]string{"status": "stepped"})
}

// debugGlobalStop handles POST /debug/global/stop — force stop current execution
func (s *Server) debugGlobalStop(w http.ResponseWriter, r *http.Request) {
	s.globalDebug.Disable() // Disable stops the session internally
	writeJSON(w, 200, map[string]string{"status": "stopped"})
}

// debugGlobalEvaluate handles POST /debug/global/evaluate
func (s *Server) debugGlobalEvaluate(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Expr string `json:"expr"`
	}
	if err := readJSON(r, &req); err != nil {
		writeJSON(w, 400, map[string]string{"error": err.Error()})
		return
	}
	if req.Expr == "" {
		writeJSON(w, 400, map[string]string{"error": "empty expression"})
		return
	}

	// If a debug session is active, only evaluate when paused — otherwise the
	// expression refers to DSL locals (e.g. Запрос.Текст) that don't exist
	// outside the paused frame, and a standalone fallback would return nil,
	// making the watch panel flicker every poll between paused and running.
	sess := s.globalDebug.Session()
	if sess != nil {
		snap := sess.Snapshot()
		if snap.State != debugger.StatePaused {
			writeJSON(w, 200, debugger.EvaluateResult{
				IsError: true,
				Error:   "interpreter is not paused",
			})
			return
		}
		result := sess.Evaluate(req.Expr, func(expr string) (any, error) {
			return standaloneEval(s, expr)
		})
		// Convert Value to a string so JSON-marshaling never silently drops
		// unexported fields (e.g. *Map, *Array) — client always gets a readable string.
		result.Value = debugger.FormatValue(result.Value)
		writeJSON(w, 200, result)
		return
	}

	// No debug session — fall back to standalone evaluation (e.g. "2+2").
	val, err := standaloneEval(s, req.Expr)
	if err != nil {
		writeJSON(w, 200, debugger.EvaluateResult{
			IsError: true,
			Error:   err.Error(),
		})
		return
	}
	writeJSON(w, 200, debugger.EvaluateResult{
		Value: debugger.FormatValue(val),
		Type:  debugger.GetTypeName(val),
	})
}

// standaloneEval parses and evaluates a DSL expression
func standaloneEval(s *Server, expr string) (any, error) {
	l := lexer.New(expr, "<console>")
	p := parser.New(l)
	parsed, err := p.ParseExpr()
	if err != nil {
		return nil, err
	}

	tmpInterp := interpreter.New()
	tmpInterp.LookupProc = s.reg.GetModuleProc
	result := tmpInterp.EvalExpr(parsed, nil)
	return result, nil
}
