package ui

import (
	"fmt"
	"html"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"github.com/ivantit66/onebase/internal/metadata"
	"github.com/ivantit66/onebase/internal/storage"
)

func TestParseFormNumber_AcceptsCommaAndDot(t *testing.T) {
	tests := map[string]string{
		"12,345": "12.345",
		"12.345": "12.345",
		"-0,5":   "-0.5",
		"+,75":   "0.75",
		" 1000 ": "1000",
	}
	for input, want := range tests {
		got, err := parseFormNumber(input)
		if err != nil {
			t.Errorf("parseFormNumber(%q): %v", input, err)
			continue
		}
		if got.String() != want {
			t.Errorf("parseFormNumber(%q) = %s, ожидалось %s", input, got, want)
		}
	}
}

func TestParseFormNumber_RejectsInvalidInput(t *testing.T) {
	for _, input := range []string{"12,3,4", "12.3.4", "1 000", "abc", "12x", ","} {
		if _, err := parseFormNumber(input); err == nil {
			t.Errorf("parseFormNumber(%q) должен вернуть ошибку", input)
		}
	}
}

// Регрессия #384: запятая в number(15,3) должна нормализоваться до decimal до
// границы storage и одинаково записываться в PostgreSQL и SQLite.
func TestSubmit_NumberWithCommaSaved(t *testing.T) {
	entity := &metadata.Entity{
		Name: "Тариф",
		Kind: metadata.KindCatalog,
		Fields: []metadata.Field{
			{Name: "Значение", Type: metadata.FieldTypeNumber, Length: 15, Scale: 3},
		},
	}
	s, ctx := newSubmitTestServer(t, []*metadata.Entity{entity})
	request := reqWithChi(http.MethodPost, "/ui/catalog/Тариф/new", url.Values{
		"Значение": {"12345,678"},
	}, map[string]string{"entity": entity.Name})
	response := httptest.NewRecorder()

	s.submit(response, request)

	if response.Code != http.StatusSeeOther {
		t.Fatalf("ожидался 303, получен %d: %s", response.Code, response.Body.String())
	}
	rows, err := s.store.List(ctx, entity.Name, entity, storage.ListParams{})
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) != 1 {
		t.Fatalf("ожидалась одна запись, получено %d", len(rows))
	}
	if got := fmt.Sprint(rows[0]["Значение"]); got != "12345.678" {
		t.Errorf("Значение = %q, ожидалось 12345.678", got)
	}
}

func TestParseSubmitForm_InvalidNumberReturnsWarningBeforeStorage(t *testing.T) {
	entity := &metadata.Entity{
		Name:   "Тариф",
		Kind:   metadata.KindCatalog,
		Fields: []metadata.Field{{Name: "Значение", Type: metadata.FieldTypeNumber, Length: 15, Scale: 3}},
	}
	s, _ := newSubmitTestServer(t, []*metadata.Entity{entity})
	request := reqWithChi(http.MethodPost, "/ui/catalog/Тариф/new", url.Values{
		"Значение": {"12,3x"},
	}, map[string]string{"entity": entity.Name})
	response := httptest.NewRecorder()

	_, _, _, _, ok := s.parseSubmitForm(response, request, entity, nil)

	if ok {
		t.Fatal("некорректное число не должно доходить до записи")
	}
	if response.Code != http.StatusBadRequest {
		t.Fatalf("статус = %d, ожидался 400", response.Code)
	}
	if body := html.UnescapeString(response.Body.String()); !strings.Contains(body, "поле \"Значение\": некорректное число") {
		t.Errorf("нет понятного предупреждения: %q", body)
	} else {
		if !strings.Contains(body, "<form") {
			t.Errorf("ошибка показана отдельной текстовой страницей, а не в форме: %q", body)
		}
		if !strings.Contains(body, `value="12,3x"`) {
			t.Errorf("форма потеряла введённое значение: %q", body)
		}
	}
}

func TestNumberInputsHaveDecimalKeyboardAndPattern(t *testing.T) {
	for name, source := range map[string]string{
		"autogenerated": templateSource(),
		"managed":       tplManagedForm,
	} {
		if !strings.Contains(source, `inputmode="decimal"`) {
			t.Errorf("%s форма не включает десятичную клавиатуру", name)
		}
		if !strings.Contains(source, `pattern="[+-]?([0-9]+([.,][0-9]+)?|[.,][0-9]+)"`) {
			t.Errorf("%s форма не ограничивает ввод числовым шаблоном", name)
		}
	}
}
